# Default values for my-app
replicaCount: 2

image:
  repository: 692859952726.dkr.ecr.us-east-1.amazonaws.com/devops_interviewer
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-registry-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: amitmaman.online
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env: []
  # - name: ENV_VAR
  #   value: "value"

configMaps: []
  # - name: config-name
  #   data:
  #     key: value

secrets: []
  # - name: secret-name
  #   data:
  #     key: value

healthCheck:
  livenessPath: /health
  readinessPath: /health

ecr:
  username: AWS
  password: ""  # This should be set via --set or environment variable
